config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  resources :sessions, only: %i(new create destroy)
  namespace :admin do
    resources :users
  end
  resources :users, only: %i(new create show edit update)
  resources :labels
  resources :groups
  resources :group_users, only: %i(index create destroy)
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels

  has_one_attached :image

  validates :theme, presence: true
  validates :content, presence: true

  scope :search_theme, -> (search) { where("theme LIKE ?", "%#{search}%") }
  scope :search_status, -> (search) { where(status: search) }
  scope :search_label, -> (search) { where(id: TaskLabel.where(label_id: search).pluck(:task_id)) }
  scope :near_limit, -> { where(time_limit: Time.zone.today..Time.zone.today + 2).where.not(status: 3) }
  scope :time_over, -> { where("time_limit <= ?", Time.zone.today - 1).where.not(status: 3) }
  scope :remind_limit, -> { where(time_limit: Time.zone.today + 7).where.not(status: 3) }

  enum status: { yet: 1, doing: 2, done: 3 }
  enum priority: { low: 1, middle: 2, high: 3 }

  def start_time
    self.time_limit
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i(show edit update destroy)
  before_action :authenticate_user, only: %i(index new show edit)

  def index
    @tasks = data_select.order(created_at: "DESC").page(params[:page]).per(10)
    @tasks = data_select.order(time_limit: "ASC").page(params[:page]).per(10) if params[:sort_expired].present?
    @tasks = data_select.order(priority: "DESC").page(params[:page]).per(10) if params[:sort_priority].present?

    if params[:search].present?
      if params[:theme].present? && params[:status].present? && params[:label_ids].present?
        @tasks = data_select.search_theme(params[:theme]).search_status(params[:status]).search_label(params[:label_ids]).page(params[:page]).per(10)

      elsif params[:theme].present? && params[:status].present? && params[:label_ids].blank?
        @tasks = data_select.search_theme(params[:theme]).search_status(params[:status]).page(params[:page]).per(10)

      elsif params[:theme].present? && params[:status].blank? && params[:label_ids].present?
        @tasks = data_select.search_theme(params[:theme]).search_label(params[:label_ids]).page(params[:page]).per(10)

      elsif params[:theme].blank? && params[:status].present? && params[:label_ids].present?
        @tasks = data_select.search_theme(params[:theme]).search_status(params[:status]).page(params[:page]).per(10)

      elsif params[:theme].present? && params[:status].blank? && params[:label_ids].blank?
        @tasks = data_select.search_theme(params[:theme]).page(params[:page]).per(10)

      elsif params[:theme].blank? && params[:status].present? && params[:label_ids].blank?
        @tasks = data_select.search_status(params[:status]).page(params[:page]).per(10)

      elsif params[:theme].blank? && params[:status].blank? && params[:label_ids].present?
        @tasks = data_select.search_label(params[:label_ids]).page(params[:page]).per(10)

      end
    end
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if status_back
      render :new
    elsif @task.save
      redirect_to tasks_path, success: "タスクの登録が完了しました。"
    else
      render :new
    end
  end

  def show
    @task.read_unread = true
    @task.save
  end

  def edit
    label_data = @task.labels.all
    unless label_data.blank?
      @task.labels.build
    end
  end

  def update
    if status_back
      redirect_to tasks_path
    elsif @task.update(task_params)
      redirect_to tasks_path, success: "タスクの編集が完了しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, danger: "タスクを削除しました"
  end

  private

  def task_params
    params.require(:task).permit(:theme, :content, :priority, :status, :image, :time_limit, :read_unread, :user_id, label_ids:[])
  end

  def data_select
    current_user.tasks.select(:id, :theme, :content, :priority, :status, :time_limit, :read_unread, :user_id, :created_at, :updated_at)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def status_back
    params[:back]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def read_unread(object)
    if object == true
      "既読"
    else
      "未読"
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>
  <% if @task.errors.any? %>
    <h2><%= @task.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :"タスク概要" %>
    <%= f.text_field :theme, id: "task_theme", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"タスク詳細" %>
    <%= f.text_area :content, id: "task_content", class: "form-control", row: 8 %>
  </div>
  <div class="form-group">
    <%= f.label :"優先順位" %>
    <%= f.select :priority, selection_from_enum(Task, :priority), {}, id: "task_priority", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"ステータス" %>
    <%= f.select :status, selection_from_enum(Task, :status), {}, id: "task_status", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"期限" %>
    <%= f.date_field :time_limit, id: "time_limit", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"画像添付" %>
    <%= f.file_field :image %>
    <p><%= link_to "#{@task.image.filename}", url_for(@task.image), class: "btn btn-info" if @task.image.attached? %><p>
  </div>
  <div class="form-group">
    <%= f.label :"ラベル一覧" %>
    <%= f.collection_check_boxes(:label_ids, current_user.labels.all, :id, :label) do |t| %>
     <% t.label { t.check_box + t.text } %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "post", id: "task_post", class: "btn btn-primary" %>
    <%= link_to "back", tasks_path, class: "btn btn-info" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h3><%= t('view.edit_title') %></h3>
  <%= render "form" %>
</div>

app/views/tasks/index.html.erb
<h3><%= t('view.index_title') %></h3>
<div class="links">
  <%= link_to t('view.post_task'), new_task_path, class:"btn btn-primary" %>
  <%= link_to t('view.sort_time_limit'), tasks_path(sort_expired: "true"), class:'btn btn-info btn-links' %>
  <%= link_to t('view.sort_priority'), tasks_path(sort_priority: "true"), class:'btn btn-info btn-links' %>
  <%= link_to "新規ラベル登録", labels_path, class: "btn btn-primary" %>
  <%= link_to "グループ一覧", groups_path, class: "btn btn-primary" %>
</div>

<%= form_with(url: tasks_path, method: :get, local: true) do |f| %>
  <div class="form-group search-fields">
    <%= f.label :"概要検索" %>
    <%= f.text_field :theme, class: "search-form", id: "theme_search" %>
    <%= f.label :"ステータス検索" %>
    <%= f.select :status, selection_from_enum(Task, :status), include_blank: :true, id: "search_status"  %>
    <%= f.label :"ラベル検索" %>
    <%= f.select :label_ids, current_user.labels.all.collect { |l| [l.label, l.id] }, include_blank: :true, id: "search_label" %>
    <%= f.hidden_field :search, value: "true" %>
    <%= f.submit t('view.search_task'), name: nil, id: "exec_search", class: "btn-primary btn-search" %>
  </div>
<% end %>

<div class="pagination"><%= paginate @tasks %></div>

<table class="table table-striped task-table">
  <thead>
    <tr>
      <th><%= t('view.theme') %></th>
      <th><%= t('view.content') %></th>
      <th><%= t('view.priority') %></th>
      <th><%= t('view.status') %></th>
      <th><%= t('view.time_limit') %></th>
      <th><%= t('view.post_time') %></th>
      <th>既読・未読</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td class="task_row" ><%= task.theme %></td>
      <td><%= task.content %></td>
      <td class="priority_row"><%= t("view.#{task.priority}") %></td>
      <td class="status_row"><%= t("view.#{task.status}") %></td>
      <td><%= task.time_limit %></td>
      <td><%= task.created_at.strftime("%Y-%m-%d") %></td>
      <td><%= read_unread(task.read_unread) %><td>
      <td><%= link_to t('view.show'), task_path(task.id), class: "btn btn-info" %></td>
      <td><%= link_to t('view.edit'), edit_task_path(task.id), class: "btn btn-info" %></td>
      <td><%= link_to t('view.destroy'), task_path(task.id), method: :delete, data: { confirm: t('view.confirm') }, class: "btn btn-danger" %></td>
      <td class="label_row">
      <% task.labels.each do |label| %>
       <%= label.label %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
<table>

<%= month_calendar events: @tasks do |date, tasks| %>
  <%= date %>
  <% tasks.each do |task| %>
    <div>
      <%= task.theme %>
    </div>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<div class="container">
  <h3><%= t('view.new_title') %></h3>
  <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<div class="container">

  <h3 class="show-title"><strong><%= t('view.show_title') %></h3>

  <table class="table table-task-show">
    <tr>
      <th><%= t('view.theme') %></th>
      <td><%= @task.theme %></td>
    </tr>
    <tr>
      <th><%= t('view.content') %></th>
      <td><%= @task.content %></td>
    </tr>
    <tr>
      <th><%= t('view.priority') %></th>
      <td><%= t("view.#{@task.priority}") %></td>
    </tr>
    <tr>
      <th><%= t('view.status') %></th>
      <td><%= t("view.#{@task.status}") %></td>
    </tr>
    <tr>
      <th><%= t('view.time_limit') %></th>
      <td><%= @task.time_limit %></td>
    </tr>
    <tr>
      <th>ラベル</th>
      <td>
        <% @task.labels.each do |label| %>
         <%= label.label %>
        <% end %>
      </td>
    </tr>
  </table>
  <p><%= link_to "#{@task.image.filename}", url_for(@task.image), class: "btn btn-info" if @task.image.attached? %></p>

  <%= link_to t('view.edit'), edit_task_path(@task.id), class: "btn btn-primary" %>
  <%= link_to t('view.index'), tasks_path, class: "btn btn-info" %>
</div>