config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  resources :sessions, only: %i(new create destroy)
  namespace :admin do
    resources :users
  end
  resources :users, only: %i(new create show edit update)
  resources :labels
  resources :groups
  resources :group_users, only: %i(index create destroy)
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels

  validates :label, presence: true
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :authenticate_user, only: %i(index new show edit)
  before_action :set_label, only: %i(show edit update destroy)

  def index
    @labels = current_user.labels.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_path, success: "ラベルを追加しました"
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if status_back
      redirect_to tasks_path
    elsif @label.update(label_params)
      redirect_to labels_path, success: "ラベルの編集が完了しました"
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path, danger: "ラベルを削除しました"
  end

  private

  def label_params
    params.require(:label).permit(:label, :user_id)
  end

  def set_label
    @label = current_user.labels.find(params[:id])
  end

  def status_back
    params[:back]
  end

end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: @label, local: true) do |f| %>
  <% if @label.errors.any? %>
    <h2><%= @label.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :"ラベル名" %>
    <%= f.text_field :label, class: "form-control", id: "label_create" %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "post", id: "label_post", class: "btn btn-primary" %>
    <%= link_to "back", labels_path, class: "btn btn-info" %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h3>ラベル編集</h3>
<%= render "form" %>

app/views/labels/index.html.erb
<%= link_to "ラベル作成", new_label_path, class:"btn btn-primary" %>
<%= link_to "タスク一覧へ", tasks_path, class:"btn btn-info" %>
<table class="table table-striped task-table">
  <thead>
    <tr>
      <th><%= t('view.label_index') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @labels.each do |label| %>
    <tr>
      <td><%= label.label %></td>
      <td><%= link_to t('view.show'), label_path(label.id), class: "btn btn-info" %></td>
      <td><%= link_to t('view.edit'), edit_label_path(label.id), class: "btn btn-info" %></td>
      <td><%= link_to t('view.destroy'), label_path(label.id), method: :delete, data: { confirm: t('view.confirm') }, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
<table>

<%= column_chart Label.where.not(user_id: current_user.id).group(:label).count %>

app/views/labels/new.html.erb
<h3>新ラベル作成</h3>
<%= render "form" %>

app/views/labels/show.html.erb
<div class="container">

  <table class="table table-task-show">
    <tr>
      <th>ラベル名</th>
      <td><%= @label.label %></td>
    </tr>
  </table>

  <%= link_to t('view.edit'), edit_label_path(@label.id), class: "btn btn-primary" %>
  <%= link_to t('view.index'), labels_path, class: "btn btn-info" %>
</div>