config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  resources :sessions, only: %i(new create destroy)
  namespace :admin do
    resources :users
  end
  resources :users, only: %i(new create show edit update)
  resources :labels
  resources :groups
  resources :group_users, only: %i(index create destroy)
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :group_users, source: :user
  has_many :group_users, dependent: :destroy, source: :user
  validates :group_name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user, only: %i(index new show edit)
  before_action :set_group, only: %i(show edit update destroy)

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to groups_path, notice: "新規グループを登録しました"
    else
      render :new
    end
  end

  def edit; end

  def update
    if status_back
      redirect_to groups_path
    elsif @group.update(group_params)
      redirect_to groups_path, success: "グループの編集が完了しました"
    else
      render :edit
    end
  end

  def show
    @group_user = current_user.group_users.find_by(group_id: @group.id)
    @leader = User.find_by(id: @group.user_id)
  end

  def destroy
    @group.destroy
    redirect_to groups_path, danger: "グループを削除しました"
  end

  private

  def group_params
    params.require(:group).permit(:group_name, :content, :user_id)
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def status_back
    params[:back]
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <% if @group.errors.any? %>
    <h2><%= @group.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :"グループ名" %>
    <%= f.text_field :group_name, class: "form-control" %>
  </div>
  <div>
    <%= f.label :"活動内容" %>
    <%= f.text_field :content, class: "form-control" %>
   </div>

  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "post", class: "btn btn-primary" %>
    <%= link_to "back", groups_path, class: "btn btn-info" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h3>グループ編集</h3>
<%= render "form" %>

app/views/groups/index.html.erb
<%= link_to "グループ作成", new_group_path, class:"btn btn-primary" %>
<%= link_to "タスク一覧へ", tasks_path, class:"btn btn-info" %>
<table class="table table-striped task-table">
  <thead>
    <tr>
      <th>グループ一覧</th>
      <th>活動内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
    <tr>
      <td><%= group.group_name %></td>
      <td><%= group.content %></td>
      <td>
        <% unless group.user_id == current_user.try(:id) %>
          <% if group.group_users.find_by(user_id: current_user.id).present? %>
            <%= link_to "脱退する", group_user_path(id: group.group_users.ids), method: :delete, class: "btn btn-danger" %>
          <% else %>
            <%= link_to "参加する", group_users_path(group_id: group.id), method: :post, class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </td>
      <td>
        <% if group.group_users.find_by(user_id: current_user.id).present? %>
          <%= link_to t('view.show'), group_path(group.id), class: "btn btn-info" %>
        <% end %>
      </td>
      <td>
        <% if group.user_id == current_user.try(:id) %>
          <%= link_to t('view.edit'), edit_group_path(group.id), class: "btn btn-info" %>
        <% end %>
      </td>
      <td>
        <% if group.user_id == current_user.try(:id) %>
          <%= link_to t('view.destroy'), group_path(group.id), method: :delete, data: { confirm: t('view.confirm') }, class: "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
<table>

app/views/groups/new.html.erb
<h3>新規グループ作成</h3>
<%= render "form" %>

app/views/groups/show.html.erb
<div class="container">

  <table class="table">
    <tr>
      <th>グループ名</th>
      <td><%= @group.group_name %></td>
    </tr>
    <tr>
      <th>活動内容</th>
      <td><%= @group.content %></td>
    </tr>
  </table>

  <h4>メンバータスク一覧</h4>
  <p>グループオーナー：<%= @leader.name %>のタスク</p>
  <table class="table">
    <tr>
      <th>タスク名</th>
      <th>優先順位</th>
      <th>ステータス</th>
      <th>期限</th>
    <tr>
    <% @leader.tasks.each do |task| %>
    <tr>
      <td><%= task.theme %></td>
      <td><%= t("view.#{task.priority}")   %></td>
      <td><%= t("view.#{task.status}")   %></td>
      <td><%= task.time_limit %></td>
    </tr>
    <% end %>
  </table>

  <% unless @group_user.nil? %>
    <table class="table">
      <tr>
        <th>ユーザ名</th>
        <th>タスク名</th>
        <th>優先順位</th>
        <th>ステータス</th>
        <th>期限</th>
      <tr>
    <% @group_user.user.tasks.each do |user| %>
      <tr>
        <td><%= user.user.name %></td>
        <td><%= user.theme %></td>
        <td><%= t("view.#{user.priority}")  %></td>
        <td><%= t("view.#{user.status}")  %></td>
        <td><%= user.time_limit %></td>
      </tr>
    <% end %>
    </table>
  <% end %>

  <% unless @group.user_id == current_user.try(:id)%>
    <% if @group_user.present? %>
      <%= link_to "脱退する", group_user_path(id: @group_user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "参加する", group_users_path(group_id: @group.id), method: :post, class: "btn btn-primary" %>
    <% end %>
  <% end %>
  <%= link_to t('view.edit'), edit_group_path(@group.id), class: "btn btn-primary" %>
  <%= link_to t('view.index'), groups_path, class: "btn btn-info" %>
</div>