config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :tasks
  resources :sessions, only: %i(new create destroy)
  namespace :admin do
    resources :users
  end
  resources :users, only: %i(new create show edit update)
  resources :labels
  resources :groups
  resources :group_users, only: %i(index create destroy)
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <header class="page-header">
        <h1><%= t('view.header') %></h1>
        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id), class: "btn btn-primary" %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "btn btn-danger" %>
          <%= link_to "参加グループ", group_users_path, class: %q(btn btn-default) %>
          <% if current_user.admin? %>
            <%= link_to "管理画面", admin_users_path, class: "btn btn-success"%>
          <% end %>
        <% else %>
          <%= link_to "Sign up", new_user_path, class: "btn btn-primary" %>
          <%= link_to "Login", new_session_path, class: "btn btn-primary" %>
        <% end %>
      </header>
      <% flash.each do |task_type, task| %>
        <div class="alert alert-<%= task_type %>"><%= task %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>